# Config file
#
# Fill out this file using the instructions in the README
#
# A few sane default values are filled in, feel free to change them per
#   your projects' needs


# YOUTUBE Data API
YOUTUBE:
  OAUTH_CLIENT_SECRETS_FILE:


# AWS credentials for Mechanical Turk
AWS:
  ACCESS_KEY_ID:
  SECRET_ACCESS_KEY:


# HIT attributes
# More info here:
# https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMechanicalTurkRequester/mturk-hits-attributes.html
MTURK:
  TITLE:
  DESCRIPTION:
  KEYWORDS:
  REWARD: 0.0
  MAX_ASSIGNMENTS: 0
  LIFETIME_SECONDS: 604800 # 1 week
  ASSIGNMENT_DURATION_SECONDS: 3600 # 1 hour
  AUTO_APPROVAL_SECONDS: 259200 # 3 days


# Survey options
SURVEY:
  SURVEY_VIDEOS: 5 # Number of videos per survey
  SURVEY_PLAYLIST: # Title of the youtube playlist for un-annotated videos
  QUALIFICATION_VIDEOS: 5
  QUALIFICATION_PLAYLIST: # Title of the youtube playlist for qualification videos
